name: PublishDocumentation

on: 
  push:
    tags: '*.*.*'

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: jtcrowson/publish-jazzy-docs@master
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        config: jazzy.yaml
        resourcesFilePath: docs-source/img
